# Site settings
title: "Michaels Blog"
email: 
description: "My blog about C# / .NET development including topics like Xamarin, Azure and other cool stuff"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "My name is Michael and I am a Software Engineer @ Sivantos GmbH in Erlangen.<br/> This blog is all about C# / .NET development including topics like Xamarin, Azure and other cool stuff. <br /><br /> Enjoy it :-)"
title_image: "https://de.gravatar.com/userimage/69692369/8bb38fb302b5fce5136b42518f84eeae.jpg?size=256"
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Google services
google_analytics: UA-79137322-1

# Social usernames/URLs
twitter_username: dragon16111
github_username:  dragon160
xing_username: Michael_Probst19

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
