# Site settings
title: "Michaels Blog"
email: 
description: "My blog about C# / .NET development including topics like Xamarin, Azure and other cool stuff"
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "My name is Michael and I am a Software Engineer @ Zühlke Engineering in Munich.<br/> This blog is all about C# / .NET development including topics like Xamarin, Azure and other cool stuff. <br /><br /> Enjoy it :-)"
title_image: "https://secure.gravatar.com/avatar/3d065a29dbf45e6c57aeb61c757770da?s=128"
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: dragon16111
github_username:  dragon160
xing_username: Michael_Probst19

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
